In [1]:
#### Miscellaneous functions
def sigmoid(z):
    """The sigmoid function."""
    return 1.0/(1.0+np.exp(-z))

def sigmoid_prime(z):
    """Derivative of the sigmoid function."""
    return sigmoid(z)*(1-sigmoid(z))

In [2]:
#### Libraries
# Standard library
import random

# Third-party libraries
import numpy as np

class Network(object):

    def __init__(self, sizes):
        """The list ``sizes`` contains the number of neurons in the
        respective layers of the network.  For example, if the list
        was [2, 3, 1] then it would be a three-layer network, with the
        first layer containing 2 neurons, the second layer 3 neurons,
        and the third layer 1 neuron.  The biases and weights for the
        network are initialized randomly, using a Gaussian
        distribution with mean 0, and variance 1.  Note that the first
        layer is assumed to be an input layer, and by convention we
        won't set any biases for those neurons, since biases are only
        ever used in computing the outputs from later layers."""
        self.num_layers = len(sizes)
        self.sizes = sizes
        self.biases = [np.random.randn(y, 1) for y in sizes[1:]]
        self.weights = [np.random.randn(y, x)
                        for x, y in zip(sizes[:-1], sizes[1:])]

    def feedforward(self, a):
        """Return the output of the network if ``a`` is input."""
        for b, w in zip(self.biases, self.weights):
            a = sigmoid(np.dot(w, a)+b)
        return a

    def SGD(self, training_data, epochs, mini_batch_size, eta,
            test_data=None):
        """Train the neural network using mini-batch stochastic
        gradient descent.  The ``training_data`` is a list of tuples
        ``(x, y)`` representing the training inputs and the desired
        outputs.  The other non-optional parameters are
        self-explanatory.  If ``test_data`` is provided then the
        network will be evaluated against the test data after each
        epoch, and partial progress printed out.  This is useful for
        tracking progress, but slows things down substantially."""

        training_data = list(training_data)
        n = len(X)

        if test_data:
            test_data = list(test_data)
            n_test = len(test_data)

        for j in range(epochs):
            random.shuffle(training_data)
            mini_batches = [
                training_data[k:k+mini_batch_size]
                for k in range(0, n, mini_batch_size)
            ]
            for mini_batch in mini_batches:
                self.update_mini_batch(mini_batch, eta)
            if test_data:
                print("Epoch {} : {} / {}".format(j,self.evaluate(test_data),n_test));
            else:
                print("Epoch {} complete".format(j))

    def update_mini_batch(self, mini_batch, eta):
        """Update the network's weights and biases by applying
        gradient descent using backpropagation to a single mini batch.
        The ``mini_batch`` is a list of tuples ``(x, y)``, and ``eta``
        is the learning rate."""
        nabla_b = [np.zeros(b.shape) for b in self.biases]
        nabla_w = [np.zeros(w.shape) for w in self.weights]
        for x, y in mini_batch:
            delta_nabla_b, delta_nabla_w = self.backprop(x, y)
            nabla_b = [nb+dnb for nb, dnb in zip(nabla_b, delta_nabla_b)]
            nabla_w = [nw+dnw for nw, dnw in zip(nabla_w, delta_nabla_w)]
        self.weights = [w-(eta/len(mini_batch))*nw
                        for w, nw in zip(self.weights, nabla_w)]
        self.biases = [b-(eta/len(mini_batch))*nb
                       for b, nb in zip(self.biases, nabla_b)]

    def backprop(self, x, y):
        """Return a tuple ``(nabla_b, nabla_w)`` representing the
        gradient for the cost function C_x.  ``nabla_b`` and
        ``nabla_w`` are layer-by-layer lists of numpy arrays, similar
        to ``self.biases`` and ``self.weights``."""
        nabla_b = [np.zeros(b.shape) for b in self.biases]
        nabla_w = [np.zeros(w.shape) for w in self.weights]
        # feedforward
        activation = x
        activations = [x] # list to store all the activations, layer by layer
        zs = [] # list to store all the z vectors, layer by layer
        for b, w in zip(self.biases, self.weights):
            z = np.dot(w, activation)+b
            zs.append(z)
            activation = sigmoid(z)
            activations.append(activation)
        # backward pass
        delta = self.cost_derivative(activations[-1], y) * \
            sigmoid_prime(zs[-1])
        nabla_b[-1] = delta
        nabla_w[-1] = np.dot(delta, activations[-2].transpose())
        # Note that the variable l in the loop below is used a little
        # differently to the notation in Chapter 2 of the book.  Here,
        # l = 1 means the last layer of neurons, l = 2 is the
        # second-last layer, and so on.  It's a renumbering of the
        # scheme in the book, used here to take advantage of the fact
        # that Python can use negative indices in lists.
        for l in range(2, self.num_layers):
            z = zs[-l]
            sp = sigmoid_prime(z)
            delta = np.dot(self.weights[-l+1].transpose(), delta) * sp
            nabla_b[-l] = delta
            nabla_w[-l] = np.dot(delta, activations[-l-1].transpose())
        return (nabla_b, nabla_w)

    def evaluate(self, test_data):
        """Return the number of test inputs for which the neural
        network outputs the correct result. Note that the neural
        network's output is assumed to be the index of whichever
        neuron in the final layer has the highest activation."""
        test_results = [(np.argmax(self.feedforward(x)), y)
                        for (x, y) in test_data]
        return sum(int(x == y) for (x, y) in test_results)

    def cost_derivative(self, output_activations, y):
        """Return the vector of partial derivatives \partial C_x /
        \partial a for the output activations."""
        return (output_activations-y)

In [28]:
from ucimlrepo import fetch_ucirepo 
  
# fetch dataset 
hepatitis = fetch_ucirepo(id=46) 
  
# data (as pandas dataframes) 
X = hepatitis.data.features 
y = hepatitis.data.targets 
  
# metadata 
print(hepatitis.metadata) 
  
# variable information 
print(hepatitis.variables) 

{'uci_id': 46, 'name': 'Hepatitis', 'repository_url': 'https://archive.ics.uci.edu/dataset/46/hepatitis', 'data_url': 'https://archive.ics.uci.edu/static/public/46/data.csv', 'abstract': 'From G.Gong: CMU; Mostly Boolean or numeric-valued attribute types; Includes cost data (donated by Peter Turney)', 'area': 'Health and Medicine', 'tasks': ['Classification'], 'characteristics': ['Multivariate'], 'num_instances': 155, 'num_features': 19, 'feature_types': ['Categorical', 'Integer', 'Real'], 'demographics': [], 'target_col': ['Class'], 'index_col': None, 'has_missing_values': 'yes', 'missing_values_symbol': 'NaN', 'year_of_dataset_creation': 1983, 'last_updated': 'Fri Nov 03 2023', 'dataset_doi': '10.24432/C5Q59J', 'creators': [], 'intro_paper': None, 'additional_info': {'summary': 'Please ask Gail Gong for further information on this database.', 'purpose': None, 'funded_by': None, 'instances_represent': None, 'recommended_data_splits': None, 'sensitive_data': None, 'preprocessing_descri

In [29]:
X = X.fillna(X.median())

In [30]:
training_data = X.copy()
training_data['Class'] = y.values
training_data = [(np.array(training[0:19]).reshape(19,1), np.array([training[19]])) for training in training_data.to_numpy()]
testing_data_index = sorted(random.sample(range(len(training_data)), 3))
testing_data = []
for i, training_dataset_index in enumerate(testing_data_index):
    testing_data.append(training_data[training_dataset_index])
    training_data.pop(training_dataset_index - i)
training_dataset_index = []
testing_data

[(array([[52. ],
         [ 1. ],
         [ 1. ],
         [ 1. ],
         [ 2. ],
         [ 2. ],
         [ 2. ],
         [ 2. ],
         [ 2. ],
         [ 2. ],
         [ 2. ],
         [ 2. ],
         [ 2. ],
         [ 0.7],
         [75. ],
         [55. ],
         [ 4. ],
         [21. ],
         [ 1. ]]),
  array([2.])),
 (array([[34.],
         [ 1.],
         [ 2.],
         [ 2.],
         [ 2.],
         [ 2.],
         [ 2.],
         [ 2.],
         [ 2.],
         [ 2.],
         [ 2.],
         [ 2.],
         [ 2.],
         [ 1.],
         [85.],
         [86.],
         [ 4.],
         [61.],
         [ 1.]]),
  array([2.])),
 (array([[51. ],
         [ 1. ],
         [ 2. ],
         [ 2. ],
         [ 2. ],
         [ 2. ],
         [ 2. ],
         [ 1. ],
         [ 1. ],
         [ 2. ],
         [ 1. ],
         [ 2. ],
         [ 2. ],
         [ 0.8],
         [85. ],
         [33. ],
         [ 4.5],
         [61. ],
         [ 2. ]]),
  array([2.]

In [31]:
net = Network([19, 32, 16, 2])
net.SGD(training_data, 30, 10, 3.0, test_data=testing_data)

C:\Users\301212298\AppData\Local\Temp\ipykernel_11576\1391037560.py:4: RuntimeWarning: overflow encountered in exp
  return 1.0/(1.0+np.exp(-z))
C:\Users\301212298\AppData\Local\Temp\ipykernel_11576\549624836.py:122: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  return sum(int(x == y) for (x, y) in test_results)


Epoch 0 : 0 / 3
Epoch 1 : 0 / 3
Epoch 2 : 0 / 3
Epoch 3 : 0 / 3
Epoch 4 : 0 / 3
Epoch 5 : 0 / 3
Epoch 6 : 0 / 3
Epoch 7 : 0 / 3
Epoch 8 : 0 / 3
Epoch 9 : 0 / 3
Epoch 10 : 0 / 3
Epoch 11 : 0 / 3
Epoch 12 : 0 / 3
Epoch 13 : 0 / 3
Epoch 14 : 0 / 3
Epoch 15 : 0 / 3
Epoch 16 : 0 / 3
Epoch 17 : 0 / 3
Epoch 18 : 0 / 3
Epoch 19 : 0 / 3
Epoch 20 : 0 / 3
Epoch 21 : 0 / 3
Epoch 22 : 0 / 3
Epoch 23 : 0 / 3
Epoch 24 : 0 / 3
Epoch 25 : 0 / 3
Epoch 26 : 0 / 3
Epoch 27 : 0 / 3
Epoch 28 : 0 / 3
Epoch 29 : 0 / 3
